.TH _PRINTF 1 2023-11-25 GNU

.SH NAME
.B _printf \- custom format and print data
.SH SYNOPSIS
.B _printf
\fIFORMAT\fR

.SH DESCRIPTION
.B _printf
is a custom version of the printf function found in the standard library
.SH OPTIONS
.TP
.B \-c
prints single charcter
.TP
.B \-s
prints a string
.TP 
.B \-i
prints integers
.TP
.B \-u
prints unsigned integers
.SH AUTHORS
.B Armando Luis Marrero & Angelo Garcia
.SH COPYRIGHT
.B printf foundation, we deal in printfs
